

steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/test-pro-285015/cloudBuildHelloWorld', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/test-pro-285015/cloudBuildHelloWorld']
images:
  - 'gcr.io/test-pro-285015/cloudBuildHelloWorld'

