

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/test-pro-285015/image1', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/test-pro-285015/image1']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'cloudBuildTest', '--image', 'gcr.io/test-pro-285015/image1', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
  - gcr.io/hallowed-moment-284914/image1