

steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/test-pro-285015/spring-boot', '.']
images: ['gcr.io/test-pro-285015/spring-boot']